### ISSUE TITLE
Upgrade RainbowKit

### ISSUE THREAD

**Issue by alex-grover** [badublanc/nouns-builder-components#8]
The current version of RK doesn’t support WalletConnect 2.0. It would be nice to upgrade to v0.12.15 or later.

We’ve forcibly upgraded on purple.construction and everything is working fine. From a quick glance it doesn’t look like any of the breaking changes will impact this package.

It would also be nice to swap ethers for viem, but that may be worth doing separately.

**Comment by badublanc** [comment]
@alex-grover, thanks for opening! I upgraded RainbowKit and switched out ethers for viem. I'm holding off on release until we can update the docs for users of the embed. 

#10 for reference
