### ISSUE TITLE
Provide instructions for integrating with projects that use Tailwind

### ISSUE THREAD

**Issue by alex-grover** [badublanc/nouns-builder-components#9]
The stylesheet provided with this project sets a bunch of global classes, which can interfere with project-specific classes for projects that use TW. This makes styles flaky depending on the order of imports or seemingly unrelated configuration settings which can lead to hard-to-diagnose bugs.

I think there are 2 fixes worth considering here:

- Use the TW prefix feature to make it less likely that package styles will bleed into consuming projects https://tailwindcss.com/docs/configuration#prefix
- Provide instructions for TW projects to generate classes rather than importing the stylesheet directly. We’re taking this approach with purple.construction: https://github.com/dylsteck/purple.construction/blob/main/tailwind.config.ts#L8

**Comment by badublanc** [comment]
@alex-grover, thanks for opening! I opted for tailwind prefixes, hopefully that works for you. I'm holding off on release until we can update the docs for users of the embed. 

#10 for reference

**Comment by alex-grover** [comment]
thank you!
